@Library("vps-automation@main")_

pipeline {
    agent {
        node {
            label 'host'
        }
    }

    parameters{
        choice(name: "Docker_network", choices: ["Yes", "No"], description: "Pick something")
        choice(name: "Mysql_setup", choices: ["Yes", "No"], description: "Pick something")
        choice(name: "Zabbix_java_gateway", choices: ["Yes", "No"], description: "Pick something")
        choice(name: "Zabbix_server", choices: ["Yes", "No"], description: "Pick something")
        choice(name: "Zabbix_web", choices: ["Yes", "No"], description: "Pick something")
    }

    stages {
        stage('create docker network') {
            steps {
                script {
                    if (params.Docker_network == 'Yes') {
                        sh("sudo docker network create monitoring")
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }

        stage('mysql configure') {
            environment {
                MYSQLCRED = credentials('zabbix-mysql')
            }
            steps {
                script {
                    if (params.Mysql_setup == 'Yes') {
                        zabbix.mysql_setup()
                    } else {
                        echo("This stage skipped")
                    }
                }    
            }
        }
        stage('zabbix java gateway') {
            steps {
                script {
                    if (params.Zabbix_java_gateway == 'Yes') {
                        zabbix.zabbix_java_gateway()
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }
        stage('zabbix server') {
            environment {
                MYSQLCRED = credentials('zabbix-mysql')
            }
            steps {
                script {
                    if (params.Zabbix_server == 'Yes') {
                        zabbix.zabbix_server()
                    } else {
                        echo("This stage skipped")
                    }    
                }
            }
        }
        stage('zabbix web') {
            environment {
                MYSQLCRED = credentials('zabbix-mysql')
            }
            steps { 
                script {
                    if (params.Zabbix_web == 'Yes') {
                        zabbix.zabbix_web()
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }
    }
}