pipeline {
    agent {
        node {
            label 'host'
        }
    }

    parameters {
        choice(name: 'Remove_Container', choices: ['Yes', 'No'], description: 'Pick something')
        choice(name: 'Docker_Setup', choices: ['Yes', 'No'], description: 'Pick something')
        choice(name: 'Run_Xmrig', choices: ['Yes', 'No'], description: 'Pick something')
        choice(name: 'Stop_Xmrig', choices: ['Yes', 'No'], description: 'Pick something')
    }

    options{
        disableConcurrentBuilds()
    }
    
    stages {
        stage ('Remove available container') {
            steps {
                script {
                    if (params.Remove_Container == "Yes") {
                        sh("sudo docker stop mining")
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }

        stage ('Docker setup') {
            steps {
                script {
                    if (params.Docker_Setup == "Yes") {
                        sh('sudo docker run -itd --rm --name=mining --cpus=2 ubuntu')   
                        sh('sudo docker exec -t mining bash -c "apt update && apt upgrade -y"')
                        sh('sudo docker exec -t mining bash -c "apt install wget tmux -y"')
                        sh('sudo docker exec -t mining bash -c "wget https://github.com/xmrig/xmrig/releases/download/v6.22.0/xmrig-6.22.0-jammy-x64.tar.gz"')
                        sh('sudo docker exec -t mining bash -c "tar -zxvf xmrig-6.22.0-jammy-x64.tar.gz"')
                        sh('sudo docker exec -t mining bash -c "cp /xmrig-6.22.0/xmrig /usr/local/bin/"')
                        sh("sudo docker cp jenkins/mining/xmrig_run mining:/usr/local/bin/")
                        sh("sudo docker exec -t mining bash -c 'chmod +x /usr/local/bin/xmrig_run'")
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }

        stage ('Run xmrig') {
            steps {
                script {
                    if (params.Run_Xmrig == "Yes") {
                        sh("sudo docker exec -t mining bash -c 'tmux new-session -d -s mining'")
                        sh("sudo docker exec -t mining bash -c xmrig_run")
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }

        stage ('Stop xmrig') {
            steps {
                script {
                    if (params.Stop_Xmrig == "Yes") {
                        sh("sudo docker exec -t mining bash -c 'tmux kill-session -t mining'")
                    } else {
                        echo("This stage skipped")
                    }
                }
            }
        }
    }
}