pipeline {
    agent {
        node {
            label 'host'
        }
    }

    parameters {
        choice(name: 'CHOICE', choices: ['Yes', 'No'], description: 'Pick something')
    }

    options{
        disableConcurrentBuilds()
    }
    
    stages {
        stage ('Remove available container') {
            when {
                expression {
                    prams.name == "Yes"
                }
            }
            // input {
            //     message "Do you want to delete container?"
            //     ok "Yes, delete now"
            //     submitter "admin"
            // }
            steps {
                sh 'sudo docker stop mining'
            }
        }

        stage ('Docker setup') {
            input {
                message "Run docker contaner?"
                ok "Yes, run docker now"
                submitter "admin"
            }
            steps {
                sh('sudo docker run -itd --rm --name=mining --cpus=2 ubuntu')   
                sh('sudo docker exec -t mining bash -c "apt update && apt upgrade -y"')
                sh('sudo docker exec -t mining bash -c "apt install wget tmux -y"')
                sh('sudo docker exec -t mining bash -c "wget https://github.com/xmrig/xmrig/releases/download/v6.22.0/xmrig-6.22.0-jammy-x64.tar.gz"')
                sh('sudo docker exec -t mining bash -c "tar -zxvf xmrig-6.22.0-jammy-x64.tar.gz"')
                sh('sudo docker exec -t mining bash -c "cp /xmrig-6.22.0/xmrig /usr/local/bin/"')
                sh("sudo docker cp docker/mining/xmrig_run mining:/usr/local/bin/")
                sh("sudo docker exec -t mining bash -c 'chmod +x /usr/local/bin/xmrig_run'")
            }
        }

        stage ('Run xmrig') {
            input {
                message "Run xmrig?"
                ok "Yes, run xmrig now"
                submitter "admin"
            }
            steps {
                sh("sudo docker exec -t mining bash -c 'tmux new-session -d -s mining'")
                sh("sudo docker exec -t mining bash -c xmrig_run") 
            }
        }

        stage ('Stop xmrig') {
            input {
                message "Do you want to stop xmrig?"
                ok "Yes, stop now"
                submitter "admin"
            }
            steps {
                sh("sudo docker exec -t mining bash -c 'tmux kill-session -t mining'")
            }
        }
    }
}