pipeline {
    agent {
        node {
            label "host"
        }
    }

    stages {
        stage ("Create user & group") {
            steps {
                sh("sudo groupadd --system prometheus")
                sh("sudo useradd --system -s /sbin/nologin -g prometheus prometheus")
            }
        }
        stage ("Download resources") {
            steps {
                sh("sudo wget https://github.com/prometheus/prometheus/releases/download/v2.53.2/prometheus-2.53.2.linux-amd64.tar.gz")
                sh("sudo tar -zxvf prometheus-2.53.2.linux-amd64.tar.gz")
            }
        }
        stage ("Setup prometheus daemon") {
            steps {
                sh("sudo mv prometheus-2.53.2.linux-amd64/prometheus /usr/local/bin")
                sh("sudo mv prometheus-2.53.2.linux-amd64/promtool /usr/local/bin")
                sh("sudo mkdir /etc/prometheus")
                sh("sudo mkdir /var/lib/prometheus")
                sh("sudo chown -R prometheus:prometheus /var/lib/prometheus")
                sh("sudo mv prometheus-2.53.2.linux-amd64/console_libraries /etc/prometheus")
                sh("sudo mv prometheus-2.53.2.linux-amd64/consoles /etc/prometheus")
                sh("sudo mv prometheus-2.53.2.linux-amd64/prometheus.yml /etc/prometheus")
                sh("sudo cp docker/prometheus_setup/prometheus.service /etc/systemd/system/")
                sh("sudo systemctl daemon-reload")
            }
        }
        stage ("Start prometheus service") {
            steps {
                sh("sudo systemctl start prometheus")
                sh("sudo systemctl enable --now prometheus")
            }
        }
    }
}