networks:
  monitoring_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.10.0.0/16"
          gateway: "172.10.0.1"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports: 
      - "3000:3000"
    networks: 
      monitoring_network:
        ipv4_address: "172.10.0.2"

  loki:
    image: grafana/loki
    container_name: loki
    ports: 
      - "3100:3100"
    command: -config.file=./docker/monitoring/loki/loki-config.yaml
    networks:
      monitoring_network:
        ipv4_address: "172.10.0.10"

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=./docker/monitoring/promtail/promtail-config.yaml
    networks:
      monitoring_network:
        ipv4_address: "172.10.0.11"